- name: variables form prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your USERNAME
    private: false
  - name: PASSWORD
    prompt: Please enter your PASSWORD
    private: true
  tasks:
  - name: print and check variables
    ansible.builtin.debug:
      msg: "Username is {{USERNAME}},Password is {{PASSWORD}}"