- name: variables form inventory
  hosts: localhost
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi,I am learning {{Course}},Trinaer is {{Trainer}},Duration is {{Duration}}"