- name: variables from all
  hosts: localhost
  vars_files:
  - variables.yaml
  #vars_prompt:
  #- name: PERSON
   # prompt: please enter your anme
   # private: false
  - name: WISHES
    prompt: please enter your WISHES
    private: false
  vars:
    PERSON: "siva from Play"
    WISHES: "Morning from play"
  tasks:
  - name: check variables
    vars:
      PERSON: "Siva from task"
      WISHES: "Morning from task"
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"
