- name: checking data types
  hosts: localhost
  vars:
    NAME: sivakumar
    Skills:
    - Devops
    - shell
    - ansible
    - Linux
    Experience:
      Devops: 7
      AWS: 6
      Docker: 4
    Trainer: true
  tasks:
  - name: print key and value
    ansible.builtin.debug:
      msg: "name: {{NAME}}"

  - name: print list
    ansible.builtin.debug:
      msg: "Skills: {{Skills}}"

  - name: Print map
    ansible.builtin.debug:
      msg: "Experience: {{Experience}}"

  - name: print boolean
    ansible.builtin.debug:
      msg: "Who is trainer: {{Trainer}}"  